### ISSUE TITLE
Add legacy version for 5.x

### ISSUE THREAD

**Issue by dvdsmpsn** [atlassian/homebrew-tap#10]
Check this:
https://github.com/dvdsmpsn/homebrew-tap/blob/master/atlassian-plugin-sdk-50.rb

This allows a user to install SDK 5.0.

**Comment by meliaecodes** [comment]
Hi, 

I've now created a tap for installing 5.x versions here.   If you'd like to see additional versions, please feel free to submit a request at https://ecosystem.atlassian.net/projects/ATLASSDK. 

Cheers,
Melissa Paisley
Atlassian
