### ISSUE TITLE
Migrate from deprecated checksum algorithms

### ISSUE THREAD

**Issue by RichardSimko** [atlassian/homebrew-tap#11]
I get the following logs when upgrading my atlassian-plugin-sdk through homebrew:

    ==> Upgrading atlassian/tap/atlassian-plugin-sdk
    Warning: Calling Formula.sha1 is deprecated!
    Use Formula.sha256 instead.
    /usr/local/Library/Taps/atlassian/homebrew-tap/atlassian-plugin-sdk.rb:6:in `<class:AtlassianPluginSdk>'
    Please report this to the atlassian/tap tap!

    Warning: Calling SoftwareSpec#sha1 is deprecated!
    Use SoftwareSpec#sha256 instead.
    /usr/local/Library/Taps/atlassian/homebrew-tap/atlassian-plugin-sdk.rb:6:in `<class:AtlassianPluginSdk>'
    Please report this to the atlassian/tap tap!

    Warning: Calling Resource#sha1 is deprecated!
    Use Resource#sha256 instead.
    /usr/local/Library/Taps/atlassian/homebrew-tap/atlassian-plugin-sdk.rb:6:in `<class:AtlassianPluginSdk>'
    Please report this to the atlassian/tap tap!

    ==> Downloading https://maven.atlassian.com/content/repositories/atlassian-public/com/atlassian/amps/atlassian-plugin-sdk/6.2.9/atlassian-plugin-sdk-6.2.9.tar.gz
    ######################################################################## 100.0%
    Warning: Calling Pathname#sha1 is deprecated!
    Use Pathname#sha256 instead.
    /usr/local/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

**Comment by jdbevan** [comment]
I've got this too.

**Comment by rbywater** [comment]
Just adding a "me too" as unfortunately its still an issue.

**Comment by miknight** [comment]
Just merged #12 to address this – cheers!

**Comment by rbywater** [comment]
👍 

Thanks @miknight for merging and thanks @takuya71 for the PR - all is good in the (Atlassian Homebrew Tap) world again... 😄
