### ISSUE TITLE
Error: SHA256 mismatch when using brew install

### ISSUE THREAD

**Issue by kretzschr** [atlassian/homebrew-tap#13]
While installing the **atlassian-plugin-sdk** formula using the brew commands mentioned in README.md fails with the following error message:

`Error: SHA256 mismatch
Expected: 0714f13943f857680f47491ff439d4b6134303e8f110c64a48294141f9710058
Actual: 4c9e33d67106abc609807995e8909a3d46e5140ebc34104649b24ebdece0a474
Archive: /Users/cike/Library/Caches/Homebrew/atlassian-plugin-sdk-6.2.14.tar.gz
To retry an incomplete download, remove the file above.`

**Comment by ssbarnea** [comment]
Do I sense a some lack of QA over here? Looks like somebody manage to republish the same version.

**Comment by kdubb** [comment]
FYI for those who don't know...

Until this fix happens you can:
```bash
# Generate hash
shasum -a 256 ~/Library/Caches/Homebrew/atlassian-plugin-sdk-6.2.14.tar.gz

# Update formulae
brew edit atlassian/tap/atlassian-plugin-sdk
```

This opens an editor where you can see & replace the offending hash. Your `brew install` succeeds after this.

**Comment by meliaecodes** [comment]
Thanks for the feedback, and sorry about the bug with the checksum. If you'd like to track the fix, there's a bug raised at:
https://ecosystem.atlassian.net/browse/ATLASSDK-88

**Comment by meliaecodes** [comment]
Hi Everyone, 
Thanks for your patience. 
This has now been resolved. 
Cheers,
Melissa Paisley
Atlassian
