### ISSUE TITLE
Update to 5.1.3

### ISSUE THREAD

**Issue by ranman** [atlassian/homebrew-tap#9]
Should be pretty straightforward.

**Comment by lucasle** [comment]
FYI, Atlassian plugin SDK was re-arranged to move out AMPS plugin - which is core/bundle maven plugins. We don't need to release SDK for each AMPS version any more, so the current AMPS version for 5.1.x is 5.1.11 but SDK is 5.1.1.
The next release of SDK is 5.1.2 was planned to ship with AMPS plugin version 5.1.14, thanks

**Comment by meliaecodes** [comment]
Hey, I'm closing this as it's a fairly old issue and we've now released a number of later versions. 
If you'd like to raise a request in future please feel free to create on at https://ecosystem.atlassian.net/projects/ATLASSDK
